./cloudformation/run-performance-tests.sh \
-u heshanp@wso2.com \
-f ../ballerina-performance-distribution-1.1.1-SNAPSHOT.tar.gz \
-k $PERF_PREFIX/bhashinee-ballerina.pem \
-n bhashinee-ballerina \
-j $PERF_PREFIX/apache-jmeter-5.1.1.tgz \
-o $PERF_PREFIX/jdk-8u345-linux-x64.tar.gz \
-g $PERF_PREFIX/gcviewer-1.36.jar \
-s 'wso2-ballerina-test1-' \
-b ballerina-sl-9 \
-r 'us-east-1' \
-J c5.xlarge -S c5.xlarge -N c5.xlarge -B t3a.small \
-i ../ballerina-2201.10.1-swan-lake-linux-x64.deb \
-- -d 360 -w 180 \
-i h1_transformation \
-u 100 \
-b 500 \
-s 0 -j 2G -k 2G -m 1G -l 2G
