name: Manual Branch Build

on:
    pull_request:
        branches:
            - master
    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch to build'
                required: true
                default: 'main'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with:
              ref: ${{ github.event.inputs.branch }}
          - name: Ballerina Build
            uses: ballerina-platform/ballerina-action@master
            with:
              args: 
                run
                client.bal
                -- -Cpassword=${{ secrets.PASSWORD }}
            env:
              WORKING_DIR: ./perfServer
